apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-form
  namespace: lucho00cuba
  labels:
    svc: php-form
spec:
  replicas: 3
  selector:
    matchLabels:
      svc: php-form
  template:
    metadata:
      labels:
        svc: php-form
    spec:
      containers:
      - name: php-form
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: php-form
  namespace: lucho00cuba
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 443
      targetPort: 80
  selector:
    svc: php-form