apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-form
  labels:
    svc: php-form
spec:
  replicas: 3
  selector:
    matchLabels:
      svc: php-form
  template:
    metadata:
      labels:
        svc: php-form
    spec:
      containers:
      - name: php-form
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: php-form
spec:
  ports:
    - name: http
      port: 80
  selector:
    svc: php-form