on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - main

name: Build Image Docker & Deploy Okteto
jobs:
  devflow:
    #name: CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
      - name: login to dockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
     
      - name: build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: 0lucho0/php-form:${{ github.sha }}
      #- uses: actions/checkout@master
      #- name: build and push to docker
      #  uses: docker/build-push-action@v2
      #  with:
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}
      #    repository: 0lucho0/php-form
      #    tag_with_ref: true
      #    tag_with_sha: true
      #    dockerfile: ./Dockerfile
      #    tags: "${{ github.sha }}"

      # APPLY
      #- name: context
      #  uses: okteto/context@latest
      #  with:
      #    token: ${{ secrets.OKTETO_TOKEN }}
      #  
      #- name: "Activate personal namespace"
      #  uses: okteto/namespace@master
      #  with:
      #    namespace: lucho00cuba
  #
      #- name: "Create deployment"
      #  uses: okteto/apply@master
      #  with:
      #    manifest: ./deploy/php-form.yaml

      # SET IMAGE

      - name: deploy to cluster
        uses: steebchen/kubectl@v2.0.0
        with: # defaults to latest kubectl binary version
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: set image --record deployment/php-form php-form=0lucho0/php-form:${{ github.sha }}
      - name: verify deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: v1.21.0 # specify kubectl binary version explicitly
          command: rollout status deployment/php-form

      #- name: deploy to cluster
      #  uses: steebchen/kubectl@master
      #  env:
      #    KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      #  with:
      #    args: set image --record deployment/php-form php-form=0lucho0/php-form:${{ github.sha }}
#
      #- name: Verify Deployment
      #  uses: steebchen/kubectl@master
      #  env:
      #    KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      #    KUBECTL_VERSION: "1.15"
      #  with:
      #    args: '"rollout status deployment/nginx-deployment"'
        
# https://github.com/okteto/actions